/**
 * The office asset kit, as the orchestrator sees it.
 *
 * The 3D view is not the only thing that needs to know how big a floor is: the
 * orchestrator has to know when a floor has run out of desks, and it must be able
 * to answer that without a browser attached. So it reads the same two files the
 * client does.
 *
 * Two sources, and the split is deliberate:
 *
 *  - `blocks.json` describes the *kit* — module sizes, doorways, seat names, and
 *    the core's growth ports. It is generated by the same Blender script that
 *    builds the geometry, so it cannot describe a module that does not exist.
 *  - `office.glb` is read directly for the **core's seat anchors**, rather than
 *    trusting a number written down somewhere. The named empties in the asset are
 *    the contract the org chart already refers to, and counting them is the only
 *    way to be sure the count matches the room that actually ships.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { BlockKit, OfficeBlockKind } from '@dev3d/core';

const GLB_MAGIC = 0x46546c67;
const CHUNK_JSON = 0x4e4f534a;

export interface OfficeAssetKit {
  kit: BlockKit | null;
  /** `Seat_*` names the core office actually carries, sorted. */
  coreSeatIds: string[];
  /** Why the kit is missing, when it is. */
  problem: string | null;
}

interface GltfJson {
  nodes?: Array<{ name?: string }>;
}

/**
 * Every `Seat_*` node name in a `.glb`.
 *
 * A GLB is a 12-byte header then a chunk table; the first chunk is JSON. Reading
 * it is a few dozen lines and avoids both a dependency and trusting a sidecar to
 * stay in step with the asset.
 */
export function readGlbSeatIds(path: string): string[] {
  const buffer = readFileSync(path);
  if (buffer.length < 20 || buffer.readUInt32LE(0) !== GLB_MAGIC) {
    throw new Error(`${path} is not a GLB`);
  }
  let offset = 12;
  while (offset + 8 <= buffer.length) {
    const length = buffer.readUInt32LE(offset);
    const type = buffer.readUInt32LE(offset + 4);
    const start = offset + 8;
    if (type === CHUNK_JSON) {
      const json = JSON.parse(buffer.subarray(start, start + length).toString('utf8')) as GltfJson;
      const seats = new Set<string>();
      for (const node of json.nodes ?? []) {
        const name = node.name;
        // A namespaced anchor belongs to a placed module, not to the core.
        if (typeof name === 'string' && name.startsWith('Seat_')) seats.add(name);
      }
      return [...seats].sort();
    }
    offset = start + length + ((4 - (length % 4)) % 4);
  }
  throw new Error(`${path} has no JSON chunk`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Parse `blocks.json` into a kit, dropping anything malformed.
 *
 * This file is generated rather than hand-written, but it is still read as
 * untrusted input: a half-written or hand-edited kit must degrade to "the core
 * office, no growth" rather than taking the office down.
 */
export function parseBlockKit(raw: unknown): { kit: BlockKit | null; problem: string | null } {
  if (!isRecord(raw)) return { kit: null, problem: 'blocks.json is not a JSON object.' };
  const core = raw['core'];
  if (!isRecord(core)) return { kit: null, problem: 'blocks.json has no "core" entry.' };
  const width = core['width'];
  const depth = core['depth'];
  if (typeof width !== 'number' || typeof depth !== 'number') {
    return { kit: null, problem: 'the core entry has no width/depth.' };
  }
  if (!Array.isArray(core['ports'])) return { kit: null, problem: 'the core entry has no ports.' };

  const ports = core['ports']
    .filter((port): port is Record<string, unknown> => isRecord(port))
    .map((port) => ({
      id: typeof port['id'] === 'string' ? port['id'] : '',
      x: typeof port['x'] === 'number' ? port['x'] : 0,
      z: typeof port['z'] === 'number' ? port['z'] : 0,
      dir: port['dir'],
    }))
    .filter((port): port is { id: string; x: number; z: number; dir: never } => port.id !== '' && (port.dir === 'n' || port.dir === 'e' || port.dir === 's' || port.dir === 'w'));
  if (ports.length === 0) return { kit: null, problem: 'the core entry has no usable ports.' };

  const blocks: OfficeBlockKind[] = [];
  for (const entry of Array.isArray(raw['blocks']) ? raw['blocks'] : []) {
    if (!isRecord(entry)) continue;
    const id = entry['id'];
    const blockWidth = entry['width'];
    const blockDepth = entry['depth'];
    if (typeof id !== 'string' || id === '' || typeof blockWidth !== 'number' || typeof blockDepth !== 'number') continue;
    const doors = (Array.isArray(entry['doors']) ? entry['doors'] : []).filter(
      (door): door is 'n' | 'e' | 's' | 'w' => door === 'n' || door === 'e' || door === 's' || door === 'w',
    );
    const seats = (Array.isArray(entry['seats']) ? entry['seats'] : []).filter(
      (seat): seat is string => typeof seat === 'string' && seat.startsWith('Seat_'),
    );
    const block: OfficeBlockKind = {
      id,
      name: typeof entry['name'] === 'string' ? entry['name'] : id,
      kind: typeof entry['kind'] === 'string' ? entry['kind'] : 'room',
      width: blockWidth,
      depth: blockDepth,
      doors,
      seats,
    };
    if (typeof entry['node'] === 'string' && entry['node'] !== '') block.node = entry['node'];
    if (typeof entry['room'] === 'string' && entry['room'] !== '') block.room = entry['room'];
    if (entry['fitting'] === true) block.fitting = true;
    blocks.push(block);
  }
  if (blocks.length === 0) return { kit: null, problem: 'blocks.json declares no modules.' };

  const version = typeof raw['version'] === 'number' ? raw['version'] : 1;
  const cell = typeof raw['cell'] === 'number' ? raw['cell'] : 0;
  return {
    kit: {
      version,
      cell,
      core: {
        model: typeof core['model'] === 'string' ? core['model'] : 'office.glb',
        width,
        depth,
        ports,
      },
      blocks,
    },
    problem: null,
  };
}

/**
 * Read the whole kit from a directory. Never throws: a missing or broken kit is
 * reported and the office runs with the core room only.
 */
export function loadOfficeKit(directory: string): OfficeAssetKit {
  const blocksPath = join(directory, 'blocks.json');
  const officePath = join(directory, 'office.glb');

  let coreSeatIds: string[] = [];
  let problem: string | null = null;
  try {
    coreSeatIds = readGlbSeatIds(officePath);
  } catch (error) {
    problem = `could not read ${officePath}: ${error instanceof Error ? error.message : String(error)}`;
  }

  if (!existsSync(blocksPath)) {
    return { kit: null, coreSeatIds, problem: problem ?? `no blocks.json in ${directory}` };
  }
  try {
    const parsed = parseBlockKit(JSON.parse(readFileSync(blocksPath, 'utf8')));
    return { kit: parsed.kit, coreSeatIds, problem: problem ?? parsed.problem };
  } catch (error) {
    return {
      kit: null,
      coreSeatIds,
      problem: `blocks.json is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}
