/**
 * Generated office space.
 *
 * A floor used to be one room. Now it is the core office plus a jigsaw of room
 * modules attached to it, and this is the vocabulary for that: what the kit
 * contains, where a module was placed, and how a seat inside one is named.
 *
 * Two decisions worth stating, because everything else follows from them:
 *
 *  - **The core keeps its seat names exactly as they are** (`Seat_Dev_01`). The
 *    shipped org chart already points at those names, so a floor that never grows
 *    needs no migration at all.
 *  - **A generated seat is namespaced by instance**, `B1::Seat_POD4_02`. The kit
 *    has one `Seat_POD4_02` per pod-type block, so without the instance prefix
 *    two pods would claim the same seat.
 */

/** The four sides of a module, named for the direction the wall faces. */
export type BlockEdge = 'n' | 'e' | 's' | 'w';

/**
 * What a module is *for*.
 *
 * A flat string with a documented vocabulary rather than a closed union: a
 * plugin-contributed module, or one hand-added to `blocks.json` ahead of a
 * Blender rebuild, must be placeable rather than rejected for being a kind this
 * build has not heard of. The renderer switches on `furniture`, which is the
 * narrower question it actually needs answered.
 */
export type OfficeBlockKindName =
  | 'open'
  | 'room'
  | 'meeting'
  | 'lounge'
  | 'junction'
  | 'corridor'
  | 'portal'
  | 'focus'
  | 'phone'
  | 'library'
  | 'workshop'
  | 'server'
  | 'breakroom'
  | 'boardroom'
  | 'gallery'
  | string;

/** Coarse grouping, so a UI can offer "more meeting space" as one choice. */
export type OfficeBlockCategory = 'work' | 'meet' | 'quiet' | 'support' | 'circulation' | 'fitting';

/**
 * How the inside of a module is fitted out.
 *
 * The layout of desks, tables and soft seating inside a room is not a property
 * of its size — a 6 x 6 room can be a booth, a library or a rack room — so it is
 * named separately and the Blender builder switches on it. `none` is a room you
 * walk through: a junction or a corridor.
 */
export type OfficeFurniture =
  | 'desks'
  | 'meeting'
  | 'boardroom'
  | 'lounge'
  | 'booths'
  | 'phone'
  | 'library'
  | 'workshop'
  | 'racks'
  | 'breakout'
  | 'gallery'
  | 'none';

/**
 * A loose object that dresses a module without being furniture.
 *
 * Props are what stop two rooms of the same size reading as the same room: a
 * plant, a whiteboard, a shelf, a rack of coats. They carry no seats and never
 * affect capacity — they are placed by the Blender builder, and this list is how
 * `blocks.json` records which of them a module ships with, for the console to
 * describe and for a future editor to toggle.
 */
export type OfficeProp =
  | 'plant'
  | 'tallPlant'
  | 'whiteboard'
  | 'pinboard'
  | 'shelf'
  | 'storage'
  | 'coatRack'
  | 'water'
  | 'coffee'
  | 'printer'
  | 'lockers'
  | 'lamp'
  | 'pendant'
  | 'rug'
  | 'partition'
  | 'stool'
  | 'screen'
  | 'art';

/** A doorway on the core, in world metres: its centre and outward normal. */
export interface CorePort {
  id: string;
  x: number;
  z: number;
  dir: BlockEdge;
}

/** One room module in the kit. Sizes are metres; the origin is its centre. */
export interface OfficeBlockKind {
  id: string;
  name: string;
  /** What the module is for. See {@link OfficeBlockKindName}. */
  kind: OfficeBlockKindName;
  /** Coarse grouping, for a UI that offers space by purpose. */
  category?: OfficeBlockCategory;
  /** How the inside is fitted out. Absent means `desks`. */
  furniture?: OfficeFurniture;
  /** Loose objects the module ships with. See {@link OfficeProp}. */
  props?: OfficeProp[];
  width: number;
  depth: number;
  /** Edges with a doorway. Growth attaches through these. */
  doors: BlockEdge[];
  /** `Seat_*` node names inside the module, in block-local space. */
  seats: string[];
  /** The cloneable node in the kit GLB, e.g. `Kit_pod4`. */
  node?: string;
  /**
   * The `Anchor_Room_*` node the module names itself with, so an employee seated
   * inside it is described as being in the pod rather than at the bench.
   */
  room?: string;
  /**
   * A fitting is placed rather than grown into: the doorway that connects a
   * block to the core, which has no doors and therefore can never be chosen as
   * a room.
   */
  fitting?: boolean;
}

/** The assembly kit, generated by `blender/scripts/02_office_blocks.py`. */
export interface BlockKit {
  version: number;
  /** The module grid, in metres. Reported for reference; placement is metric. */
  cell: number;
  core: {
    model: string;
    width: number;
    depth: number;
    ports: CorePort[];
  };
  blocks: OfficeBlockKind[];
}

/** Where the separator sits in a generated seat id: `B1::Seat_POD4_02`. */
export const SEAT_INSTANCE_SEPARATOR = '::';

/** One module placed on a floor, in world metres and degrees about Y. */
export interface PlacedBlock {
  /** Instance id, unique within the floor: `B1`, `B2`, … */
  id: string;
  /** The kit entry this instantiates. */
  kind: string;
  x: number;
  z: number;
  /** Rotation about Y, clockwise seen from above. */
  rotation: 0 | 90 | 180 | 270;
  /** The port this was attached through, for the record and for removal. */
  attachedTo: string;
}

/**
 * What a floor generated for itself. Absent means "the core only", which is what
 * every floor that has never outgrown its desks looks like.
 */
export interface FloorLayout {
  blocks: PlacedBlock[];
  /** When the last module was added, for the console's provenance line. */
  updatedAt?: number;
}

/** The seat ids a placed module contributes. */
export function blockSeatIds(placed: PlacedBlock, kind: OfficeBlockKind): string[] {
  return kind.seats.map((seat) => `${placed.id}${SEAT_INSTANCE_SEPARATOR}${seat}`);
}

/** Which block instance a seat belongs to, or null when it is a core seat. */
export function seatInstanceOf(seatId: string): string | null {
  const at = seatId.indexOf(SEAT_INSTANCE_SEPARATOR);
  return at === -1 ? null : seatId.slice(0, at);
}

/** The `Seat_*` node name inside the block, or the id unchanged for the core. */
export function seatNodeName(seatId: string): string {
  const at = seatId.indexOf(SEAT_INSTANCE_SEPARATOR);
  return at === -1 ? seatId : seatId.slice(at + SEAT_INSTANCE_SEPARATOR.length);
}
